version: '3.8'

services:
  web:
    build: .
    command: gunicorn myweb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myweb.settings
      - PYTHONUNBUFFERED=1
    restart: always
