# Generated by Django 5.0.4 on 2024-05-02 14:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('mcc', models.CharField(default=uuid.uuid4, editable=False, max_length=100)),
                ('fields_data', models.JSONField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('associated_configs', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, null=True)),
                ('client', models.CharField(max_length=255, null=True)),
                ('project_type', models.CharField(max_length=100, null=True)),
                ('edition', models.CharField(max_length=100, null=True)),
                ('version', models.CharField(max_length=10, null=True)),
                ('sequence_number', models.CharField(max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('span', models.CharField(blank=True, max_length=100, null=True)),
                ('pick', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
